---
- homebrew_tap:
    tap: thoughtbot/formulae

- name: dotfiles repo
  git:
    repo: "ssh://git@github.com/colinrymer/dotfiles.git"
    dest: /Users/colin/.dotfiles
    accept_hostkey: yes

- name: install dotfiles
  shell: rcup
