---
- name: thoughtbot homebrew tap
  homebrew_tap:
    tap: thoughtbot/formulae

- name: install rcm
  homebrew:
    name: rcm
    update_homebrew: yes

- name: dotfiles repo
  git:
    repo: "ssh://git@github.com/colinrymer/dotfiles.git"
    dest: "{{ lookup('env','HOME') }}/.dotfiles"
    accept_hostkey: yes

- name: install dotfiles
  shell: rcup
